Introduce Server Metadata and Iss Parameter
indieweb/indieauth pull request #102
Opened 2021-10-17 04:53 UTC by dshanske

This covers #43 and #101. Added the Iss parameter requirement as part of this PR as the Issuer Identifier had to be defined in Metadata.

This defines the metadata endpoint, notes the fallback to the old way of doing things, and requires that the iss parameter be returned by the authorization response and be verified against the metadata endpoint issuer parameter.

2021-11-02 03:07 UTC, aaronpk requested changes

2021-11-02 03:07 UTC, aaronpk commented on public/source/index.php
> +            <p>IndieAuth metadata adopts OAuth 2.0 Authorization Server Metadata[RFC8414], with the notable difference that usage of .well-known is RECOMMENDED, for compatibility with other OAuth2.0
Even though this is technically correct, this seems like it will be confusing as written. I'd recommend something like:

> ...with the notable difference that discovery of the URL happens via the IndieAuth link relation rather than the `.well-known` discovery method specified by RFC8414. For compatibility with other OAuth 2.0 implementations, use of the `.well-known` path is RECOMMENDED but optional.

2021-11-02 03:07 UTC, aaronpk commented on public/source/index.php
> +              <li><code>issuer</code> - The server's issuer identifier. The issuer identifier is a URL that uses the "https" scheme and has no query or fragment components. The identifier is the base
"base URL" is probably not the right term here. How about "MUST be a prefix of the authorization endpoint"

2021-11-02 03:26 UTC, aaronpk requested changes

2021-11-02 03:26 UTC, aaronpk commented on public/source/index.php
> +            <p>IndieAuth metadata adopts OAuth 2.0 Authorization Server Metadata[RFC8414], with the notable difference that discovery of the URL happens via the IndieAuth link relations rather than t
minor typos:

`link relations` -> `link relation`
`OAuth2.0` -> `OAuth 2.0`
`implementation` -> `implementations`

2021-11-02 03:26 UTC, aaronpk commented on public/source/index.php
> +              <li><code>issuer</code> - The server's issuer identifier. The issuer identifier is a URL that uses the "https" scheme and has no query or fragment components. The identifier MUST be a p
let's say `could be` instead of `would be`

2021-11-02 16:39 UTC, jamietanna approved these changes
:rocket: Good stuff

2021-11-03 22:47 UTC, aaronpk approved these changes

2021-11-03 22:47 UTC, merged